### ISSUE TITLE
为什么运行时提示System.NullReferenceException:“未将对象引用设置到对象的实例。”呢

### ISSUE THREAD

**Issue by gadfly3173** [RyuBAI/GPXGen#1]
System.NullReferenceException:“未将对象引用设置到对象的实例。”
和 "map.gpx不存在/有问题!回退至自动生成路径!"

**Comment by Lou1sL** [comment]
感谢关注！

首先需要说下，现在官方针对这类工具在服务器后台会对上传数据的可疑程度进行自动判断，封号，并会将封号结果上报学校。因此强烈建议在接码网站上买接码服务，然后自己调整修改代码确保合法性。（10块钱/100条，不是很贵）

然后是关于这个问题，你最好在Debug下运行下代码看下，vs会追踪到出问题的那行的，你再把那行的位置发过来我才能确定，否则不好说。

**Comment by gadfly3173** [comment]
在VS中提示
/*
System.NullReferenceException
  HResult=0x80004003
  Message=未将对象引用设置到对象的实例。
  Source=GXTY_CSharp
  StackTrace:
   at GXTY_CSharp.Program.FinRun() in D:\GXTY-1.10\Program.cs:line 103
   at GXTY_CSharp.RunForm..ctor() in D:\GXTY-1.10\RunForm.cs:line 66
   at GXTY_CSharp.Program.Main(String[] args) in D:\GXTY-1.10\Program.cs:line 17
*/
/*
System.NullReferenceException:“未将对象引用设置到对象的实例。”
GXTY_CSharp.Network.ReturnMessage.Data.get 返回 null。
*/
在程序右侧窗口中
/*
System.NullReferenceException:  未将对象引用设置到对象的实例。
在GXTY_CSharp. RunJSOM.LoadGPX(String path) 位置D: GXTY-1.1\RunJSON.cs:行号  226
map. gpx不存在/有问题!回退至自动生成路径!
*/

**Comment by Lou1sL** [comment]
问题应该修复了，试试看

**Comment by gadfly3173** [comment]
System.NullReferenceException
  HResult=0x80004003
  Message=未将对象引用设置到对象的实例。
  Source=GXTY_CSharp
  StackTrace:
   at GXTY_CSharp.RunForm..ctor() in D:\GXTY-1.10\RunForm.cs:line 69
   at GXTY_CSharp.Program.Main(String[] args) in D:\GXTY-1.10\Program.cs:line 17


问题依然存在。。。也依然提示我的map.gpx不存在/有问题
map.gpx链接:https://1drv.ms/u/s!Aqqr4BIdbCmVhl3NhFbu8oRrX8L0

**Comment by Lou1sL** [comment]
首先是第一个问题应该解决了，你试试。

不过有个事必须得说。。
因为我这个东西没打算传播，所以我没做JSON解析时的结构合法性判断。因此，如果服务器返回的值的结构是预料之外的，比如：没有成功时的返回值，那就会直接触发异常。
建议你在试的同时抓包观察下返回值是怎样的。

第二个gpx的问题，程序目前只支持如下格式的GPX：

```xml

<?xml version="1.0"?>
<gpx version="1.1">
<wpt lat="30.8874225616455" lon="121.902847290039">
    <ele>-1.15</ele>
    <time>2018-10-30T15:33:14Z</time>
</wpt>
<wpt lat="30.8874225616455" lon="121.902847290039">
    <ele>-1.15</ele>
    <time>2018-10-30T15:33:14Z</time>
</wpt>
<wpt lat="30.8873355616457" lon="121.902855690039">
    <ele>-1.15</ele>
    <time>2018-10-30T15:38:59Z</time>
</wpt>
</gpx>


```
你可以在 https://www.gpxgenerator.com/ 上生成符合格式的GPX

**Comment by Lou1sL** [comment]
总之，因为所有JSON全都没有进行合法性检查，问题也有可能再次在另一处代码出现，我比较懒得一次全部解决，也懒得再去注册小号了。。。。所以可能再有问题。。。。你可以自己试试修改，或抓包，或者再发出来。。。
